/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import audio.AePlayWave;
import audio.PlayAudio;
import java.awt.Color;
import java.awt.Font;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author lvazquez
 */
public class JuegoGato extends javax.swing.JFrame {

    private int turno;//=true;
    private boolean inicio;//false;
    private boolean finalizado= false;
    private int tirador;
   //JLabel mensaje; 
   private int limpiar;
   private int ganador;

    /**
     * Creates new form JuegoGato
     */
   
  
     /*  
   if (btn1.i
           ().equals("/images/x.png") && btn2.getText().equals("/images/x.png\"") && btn3.getText().equals("/images/x.png\""))
     
       ganador =1;
   if (ganador==1){
       JOptionPane.showMessageDialog(this, "Felicidades Jugador "+jugador1+ "Ganaste!!");
   } 
   }
       */
                
  
    public JuegoGato() {
        initComponents();
   }
     
  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jugador1 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buien.jpg"))); // NOI18N
        jLabel1.setText("Juego del Gato");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg"))); // NOI18N
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));

        jugador1.setBackground(new java.awt.Color(0, 255, 153));
        jugador1.setFont(new java.awt.Font("Informal Roman", 0, 24)); // NOI18N
        jugador1.setForeground(new java.awt.Color(153, 102, 255));
        jugador1.setText("Jugador 1:");
        jugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jugador1MouseExited(evt);
            }
        });

        jugador2.setFont(new java.awt.Font("Informal Roman", 0, 24)); // NOI18N
        jugador2.setForeground(new java.awt.Color(153, 102, 255));
        jugador2.setText("Jugador 2:");

        txtJugador1.setBackground(new java.awt.Color(255, 0, 51));
        txtJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador1ActionPerformed(evt);
            }
        });

        txtJugador2.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jugador1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jugador2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txtJugador2))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador1)
                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador2)
                    .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 236, 217));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diferenca.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }       
        // TODO add your handling code here:
        
        if (turno == 1) {
            btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn1.setActionCommand("1");
            turno = 2;
            txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn1.setActionCommand("2");
            turno = 1;
            txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
        if(btn1.getIcon().toString().equals(btn2.getIcon().toString())&&(btn1.getIcon().toString().equals(btn3.getIcon().toString()))){
       JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
        }else if(btn1.getIcon().toString().equals(btn4.getIcon().toString())&&(btn1.getIcon().toString().equals(btn7.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn1.getIcon().toString().equals(btn5.getIcon().toString())&&(btn1.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
        
        
  
        /*if (inicio && tirador && btn1.getActionCommand().isEmpty()){
           
        
          
        
        
        }
                
         )
         */
        // add(btn1);
        
      
      //btn1.setIcon(new(ImageIcon(getClass().getResource("images/x.jpg")));

    }//GEN-LAST:event_btn1ActionPerformed

    private void txtJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador1ActionPerformed

        // this.txtJugador1();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugador1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    
        
        
        
        //txtJugador1.requestFocus();
      
    }//GEN-LAST:event_jButton1ActionPerformed
       

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        btn1.setEnabled(false);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
          /* if (turno == 0 || turno == 1){
        if (btn1.getText().equals(""))
            btn1.setEnabled(false);
        turno= 0 ;
        turno= 1 ;
        
    } */
         /*   if (turno == 1){
        if (btn1.getText().equals(""))
            btn1.setEnabled(false);
        turno=0;
    } */        
              
         /*    if (turno == 0){
        if (btn1.getText().equals(""))
            btn1.setEnabled(false);
        turno=1;
    } 
           if (turno == 1){
        if (btn1.getText().equals(""))
            btn1.setEnabled(false);
        turno=0;
    } 
        */     
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
       
 if (turno == 1) {
            btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn2.setActionCommand("1");
            turno = 2;
            txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn2.setActionCommand("2");
            turno = 1;
             txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
        if(btn1.getIcon().toString().equals(btn2.getIcon().toString())&&(btn1.getIcon().toString().equals(btn3.getIcon().toString()))){
       JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
        }else if(btn2.getIcon().toString().equals(btn5.getIcon().toString())&&(btn2.getIcon().toString().equals(btn8.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
      /*    if (turno == 1){
        if (btn1.getText().equals(""))
            btn1.setEnabled(false);
        turno=0;
    } 
           if (turno == 1){
        if (btn1.getText().equals(""))
            btn1.setEnabled(false);
        turno=0;
    }  
           */
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
       
         if (turno == 1) {
            btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn3.setActionCommand("1");
            turno = 2;
             txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn3.setActionCommand("2");
            turno = 1;
             txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
         if(btn1.getIcon().toString().equals(btn2.getIcon().toString())&&(btn1.getIcon().toString().equals(btn3.getIcon().toString()))){
       JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
        }else if(btn3.getIcon().toString().equals(btn6.getIcon().toString())&&(btn3.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn3.getIcon().toString().equals(btn5.getIcon().toString())&&(btn3.getIcon().toString().equals(btn7.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
         try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
       
         if (turno == 1) {
            btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn4.setActionCommand("1");
            turno = 2;
             txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));
        } else {
            btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn4.setActionCommand("2");
            turno = 1;
             txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
         if(btn4.getIcon().toString().equals(btn5.getIcon().toString())&&(btn4.getIcon().toString().equals(btn6.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn1.getIcon().toString().equals(btn4.getIcon().toString())&&(btn1.getIcon().toString().equals(btn7.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
         try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         if (turno == 1) {
            btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn5.setActionCommand("1");
            turno = 2;
             txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn5.setActionCommand("2");
            turno = 1;
             txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
         if(btn4.getIcon().toString().equals(btn5.getIcon().toString())&&(btn4.getIcon().toString().equals(btn6.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn2.getIcon().toString().equals(btn5.getIcon().toString())&&(btn2.getIcon().toString().equals(btn8.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn1.getIcon().toString().equals(btn5.getIcon().toString())&&(btn1.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn3.getIcon().toString().equals(btn5.getIcon().toString())&&(btn3.getIcon().toString().equals(btn7.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
       try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
         if (turno == 1) {
            btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn6.setActionCommand("1");
            turno = 2;
             txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn6.setActionCommand("2");
            turno = 1;
             txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
                    
        }
         if(btn4.getIcon().toString().equals(btn5.getIcon().toString())&&(btn4.getIcon().toString().equals(btn6.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn3.getIcon().toString().equals(btn6.getIcon().toString())&&(btn3.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
         try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
         if (turno == 1) {
            btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn7.setActionCommand("1");
            turno = 2;
             txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn7.setActionCommand("2");
            turno = 1;
            txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
         if(btn7.getIcon().toString().equals(btn8.getIcon().toString())&&(btn7.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn1.getIcon().toString().equals(btn4.getIcon().toString())&&(btn1.getIcon().toString().equals(btn7.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn3.getIcon().toString().equals(btn5.getIcon().toString())&&(btn3.getIcon().toString().equals(btn7.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         if (turno == 1) {
            btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn8.setActionCommand("1");
            turno = 2;
             txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn8.setActionCommand("2");
            turno = 1;
             txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
         if(btn7.getIcon().toString().equals(btn8.getIcon().toString())&&(btn7.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn2.getIcon().toString().equals(btn5.getIcon().toString())&&(btn2.getIcon().toString().equals(btn8.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
         try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         if (turno == 1) {
            btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
            btn9.setActionCommand("1");
            turno = 2;
             txtJugador1.setBackground(new java.awt.Color(255,255, 0));
             txtJugador2.setBackground(new java.awt.Color(255,0, 51));

        } else {
            btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.png")));
            btn9.setActionCommand("2");
            turno = 1;
             txtJugador1.setBackground(new java.awt.Color(255,0, 51));
             txtJugador2.setBackground(new java.awt.Color(255,255, 0));
        }
         if(btn7.getIcon().toString().equals(btn8.getIcon().toString())&&(btn7.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn3.getIcon().toString().equals(btn6.getIcon().toString())&&(btn3.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}else if(btn1.getIcon().toString().equals(btn5.getIcon().toString())&&(btn1.getIcon().toString().equals(btn9.getIcon().toString()))){
    JOptionPane.showMessageDialog(null, "Felicidades, haz GANADO!!!") ;
}
    }//GEN-LAST:event_btn9ActionPerformed

    private void jugador1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugador1MouseExited
        // TODO add your handling code here:
       jugador1.setBackground(Color.green);
        jugador1.setFont( new Font("Tempus Sans ITC", 1, 12));
       
       
    }//GEN-LAST:event_jugador1MouseExited

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        btn2.setEnabled(false);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        btn3.setEnabled(false);
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
        btn4.setEnabled(false);
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        // TODO add your handling code here:
        btn5.setEnabled(false);
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
        btn6.setEnabled(false);
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
        btn7.setEnabled(false);
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        btn8.setEnabled(false);
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
        btn9.setEnabled(false);
    }//GEN-LAST:event_btn9MouseClicked

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel2FocusGained

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn1.setEnabled(true);
         btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn2.setEnabled(true);
         btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn3.setEnabled(true);
         btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn4.setEnabled(true);
         btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn5.setEnabled(true);
         btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn6.setEnabled(true);
         btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn7.setEnabled(true);
         btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn8.setEnabled(true);
         btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sb2461.jpg")));
         btn9.setEnabled(true);
         String jugador = JOptionPane.showInputDialog("Ingresa el nombre del primer jugador");
        txtJugador1.setText(jugador);
        jugador = JOptionPane.showInputDialog("Ingresa el nombre del segundo jugador");
         txtJugador2.setText(jugador);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
            
            
        
        
        
        
        java.awt.EventQueue.invokeLater(() -> {
            new JuegoGato().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador2;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables

    private void desabilitar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
